import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

import { Roboto } from "next/font/google";
import { Poppins } from "next/font/google";
import { Inter } from "next/font/google";

// app/providers.tsx

import { NextUIProvider } from "@nextui-org/react";
import Newsletter from "./components/Newsletter";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--roboto", // Correct usage of variable
  weight: ["100", "300", "400", "500", "700", "900"], // Available weights for Roboto
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--poppins", // Correct usage of variable
  weight: ["100", "300", "400", "500", "700", "900"], // Available weights for Roboto
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--inter", // Correct usage of variable
  weight: ["100", "300", "400", "500", "700", "900"], // Available weights for Roboto
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` ${roboto.variable}  ${poppins.variable}  ${inter.variable}`}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable}   antialiased`}
      >
        <div>
          <Header />
        </div>
        <NextUIProvider>{children}</NextUIProvider>
        <div>
          {/* <Newsletter/> */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
